### ISSUE TITLE
[BUG] При формировании отчета по SMOKI-тестам формируется не читаемый в формате Xml отчет.

### ISSUE THREAD

**Issue by goro781** [silverbulleters/add#866]
**Описание ошибки**
что конкретно происходит при формировании файла в xml не хватает параметров для выгрузки отчета в Allure. При подстановке другого файла Allure читает и выводит отчет.

**Сценарий воспроизведения** через командную строку вызываю тест: vrunner xunit "C:\Program Files\OneScript\lib\add\tests\smoke\Тесты_ОткрытиеФормКонфигурации.epf" --ibconnection /S1cdev\preprod --db-user "Сафронов Виталий" --db-pwd "***" --reportxunit "C:\Users\v.safronov\Desktop\programms\allure-2.13.3\reports\2fee622c-2016-4dbd-aeba-c48e32f14bed-testsuite.xml" --pathxunit "C:\Program Files\OneScript\lib\add\xddTestRunner.epf" --xddConfig "C:\Program Files\OneScript\lib\add\tests\smoke\smoke.example.json" --ordinaryapp 1
После прохождения теста формируется отчет ввиде xml файла: 
<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="C:\Program Files\OneScript\lib\add\tests\smoke\ - &lt;Сафронов Виталий&gt;" time="329.645" tests="729" failures="125" errors="0" skipped="1">
	<testsuite name="C:\Program Files\OneScript\lib\add\tests\smoke\ - &lt;Сафронов Виталий&gt;">
		<testsuite name="Тесты &quot;Открытие форм конфигурации&quot; - &lt;Сафронов Виталий&gt;">
			<testsuite name="Справочники - &lt;Сафронов Виталий&gt;">
				<testcase classname="Справочники - &lt;Сафронов Виталий&gt;" 
				

					
				<testcase classname="Отчеты - &lt;Сафронов Виталий&gt;" name="Отчет.ОборотнаяВедомостьПоОперативнойИнвентаризации.Форма.Отчет - &lt;Сафронов Виталий&gt;" time="0.031" status="passed"/>
			</testsuite>
		</testsuite>
	</testsuite>
</testsuites>
При  загрузки этого файла в в Allure через командную строку не формируется сам отчет.
команндная строка:
C:\Users\v.safronov\Desktop\programms\allure-2.13.3\bin>allure.bat serve C:\Users\v.safronov\Desktop\programms\allure-2.13.3\reports
В результате получаем:
Generating report to temp directory...
Could not read xml result C:\Users\v.safronov\Desktop\programms\allure-2.13.3\reports\2fee622c-2016-4dbd-aeba-c48e32f14bed-testsuite.xml: {}
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "time" (class ru.yandex.qatools.allure.model.TestSuiteResult), not marked as ignorable (8 known properties: "start", "title", "name", "description", "labels", "stop", "version", "test-cases"])
 at [Source: (sun.nio.ch.ChannelInputStream); line: 2, column: 160] (through reference chain: ru.yandex.qatools.allure.model.TestSuiteResult["time"])
        at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
        at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:823)
        at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1153)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1589)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1567)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:294)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3070)
        at io.qameta.allure.allure1.Allure1Plugin.readXmlTestSuiteFile(Allure1Plugin.java:460)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
        at io.qameta.allure.allure1.Allure1Plugin.readResults(Allure1Plugin.java:136)
        at io.qameta.allure.ReportGenerator.lambda$readResults$0(ReportGenerator.java:47)
        at java.util.ArrayList.forEach(Unknown Source)
        at io.qameta.allure.ReportGenerator.readResults(ReportGenerator.java:47)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:69)
        at io.qameta.allure.ReportGenerator.generate(ReportGenerator.java:58)
        at io.qameta.allure.Commands.generate(Commands.java:104)
        at io.qameta.allure.Commands.serve(Commands.java:129)
        at io.qameta.allure.CommandLine.run(CommandLine.java:159)
        at java.util.Optional.orElseGet(Unknown Source)
        at io.qameta.allure.CommandLine.main(CommandLine.java:88)
Report successfully generated to C:\Users\VCB8E~1.SAF\AppData\Local\Temp\1266460374779060431\allure-report
Starting web server...
2021-05-05 12:16:25.808:INFO::main: Logging initialized @3823ms to org.eclipse.jetty.util.log.StdErrLog

Шаги по воспроизведению:
1. Открыть '...'
2. Нажать '....'
3. Запустить '....'
4. Где ошибка

**Ожидаемое поведение, если бы ошибки не было**
'....'

**Скриншоты**
если применимо, приложите скриншоты

**Окружение:**

**Дополнительный контекст**

- Типовая или не типовая конфигурация ?
- Включен ли режим защиты от опасных действий
- и т.д.

**Comment by goro781** [comment]
1С:Предприятие 8.3 (8.3.17.1549) не управляемые формы
Vanessa Add 6.6.5
